//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.09 at 11:35:03 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://orange.com/api/productOrderingManagement/tmf/v2/model/business", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.tmf.dsmapi.productOrder.model;
